---
- name: Run backend container
  docker_container:
    name: yolo-backend-container
    image: "p801/yolo-backend-app:V5.1"
    state: started
    ports:
      - "{{ backend_port }}:5000"
    networks:
      - "{{ network_name }}"
    hostname: backend.local
