apiVersion: apps/v1
kind: Deployment
metadata:
  name: yolo-frontend
  labels:
    app: yolo-frontend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: yolo-frontend
  template:
    metadata:
      labels:
        app: yolo-frontend
    spec:
      containers:
      - name: yolo-frontend
        image: yolo-app-frontend:V2.0
        ports:
        - containerPort: 80
        env:
        - name: BACKEND_URL
          value: "http://yolo-backend:8000"
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "250m"
