---
- name: Provision server
  hosts: all
  become: yes
  vars_files:
    - vars.yml

  tasks:
    - name: Update
      apt:
        update_cache: yes

    - name: Install Docker and Docker Compose
      apt:
        name:
          - docker.io
          - docker-compose
        state: present

    - name: Create Docker network
      docker_network:
        name: "{{ network_name }}"
        state: present
    - name: Create MongoDB volume
      docker_volume:
        name: "{{ mongodb_volume }}"
        state: present
    - name: Copy hosts file
      copy:
        src: hosts
        dest: /etc/hosts
        owner: root
        group: root
        mode: "0644"

  roles:
    - yolo-backend
    - mongodb
    - yolo-frontend
