---
- name: Clone repository
  git:
    repo: "{{ repository_url }}"
    dest: /home/vagrant/yolo
    version: "{{ repository_version }}"

- name: Build frontend Docker image
  docker_image:
    name: "{{ yolo_frontend_image }}"
    path: /home/vagrant/yolo/frontend
    state: present

- name: Run frontend container
  docker_container:
    name: yolo-frontend-container
    image: "{{ yolo_frontend_image }}"
    ports:
      - "{{ frontend_port }}:3000"
    networks:
      - "{{ network_name }}"
    # hostname: frontend.local
