apiVersion: v1
kind: Service
metadata:
  name: yolo-frontend
spec:
  selector:
    app: yolo-frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer  # Exposes the service externally with a cloud provider's load balancer
